version: '3'
services:
  api_v1:
    build: .
    volumes:
      - './app_v1.py:/app_v1.py'
    links:
      - mongo
    ports:
      - "5000:5000"
    command: python3 app_v1.py

  api_v2:
    build: .
    volumes:
      - './app_v2.py:/app_v2.py'
    ports:
      - "5001:5001"
    command: python3 app_v2.py

  mongo: 
    container_name: my-mongodb
    image: mongo
    ports:
      - "27017:27017"

volumes:
  mongo:
  app_v1:
    driver: local
